name: Updating badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "40 * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          COMMIT_MESSAGE: "Updating badges.." # optional
          CREDLY_USER: vito-mule
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
